---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Livros básicos do D&D 5ª edição traduzidos para download"
keywords:    "D&D, 5ed, 5.0, RPG, traduzido, pdf, download, baixar, Livro do jogador, livro dos monstros, livro do mestre"
description: "Hotsite para download dos livros básicos do D&D 5ed. traduzidos e ilustrados: Temos todos: Livro do jogador, Manual dos Monstros e Guia do Mestre."
source_link: ""
favicon:     "img/favicon.ico"
touch_icon:  ""
google_analytics_key: #UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#333333'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  azul:      '#63A9DB'
  grey:      '#aaa'

kramdown:
  auto_ids:  false

